#!/usr/bin/env fish

set -l script_dir (status dirname)

set -l url 'https://dl.pstmn.io/changelog?channel=stable&platform=linux64'
# set -l regex '([\\d.]+)'
set -l jsonpath '$.changelog[0].name'

echo 'Adding executable permissions to `parse-json`'
chmod +x ./scripts/parse-json && cd ./scripts

echo 'Executing the `parse-json` script'
set -l output_version ("$script_dir/../scripts/parse-json" "$url" '' "$jsonpath")

# @fish-lsp-disable-next-line 2001
set -l spec_file (find "$script_dir" -name '*.spec' -print -quit)
set -l captured_version (sed -n 's/^Version:\\s*\\([\\d.]*\\)/\\1/p' "$spec_file")

# @fish-lsp-disable-next-line 2001
echo 'Comparing captured version ($captured_version) with current version ($output_version)'
echo "Captured version: $captured_version"
echo "Current version: $output_version"
if test "$captured_version" != "$output_version" 
  echo 'Versions are different. Updating the spec file...'
  sd $captured_version $output_version "$script_dir/rename-my-tv-series.spec" && echo 'Done!'
else
  echo 'Both versions are the same. No update needed.'
end

echo 'Removing executable permissions from `parse-json`'
chmod -x ./scripts/parse-json
