#!/usr/bin/env fish

set -l script_dir (status dirname)
set -l basename (basename "$script_dir")

echo "Updating '$basename'"

set -l url 'https://dl.pstmn.io/changelog?channel=stable&platform=linux64'
# set -l regex '([\\d.]+)'
set -l jsonpath '$.changelog[0].name'

echo 'Adding executable permissions to `parse-json`'
chmod +x "$script_dir/../scripts/parse-json"

echo 'Executing the `parse-json` script'
set -l output_version ("$script_dir/../scripts/parse-json" $url '' $jsonpath)

# @fish-lsp-disable-next-line 2001
set -l captured_version (sed -n 's/^Version:\\s*\\([\\d.]*\\)/\\1/p' "$script_dir/$basename.spec")

# Reassign the variables to use underscores instead of hyphens
set -l output_version (string replace --all '-' '_' $output_version)
set -l captured_version (string replace --all '-' '_' $captured_version)

# @fish-lsp-disable-next-line 2001
echo 'Comparing captured version ($captured_version) with current version ($output_version)'
echo "Captured version: $captured_version"
echo "Current version: $output_version"
if test "$captured_version" != "$output_version" 
  echo 'Versions are different. Updating the spec file(s)...'
  for v in (fd --glob '*.spec' $script_dir)
    sd $captured_version $output_version $v
  end && echo 'Done!'
else
  echo 'Both versions are the same. No update needed.'
end

echo 'Removing executable permissions from `parse-json`'
chmod -x "$script_dir/../scripts/parse-json"

echo "Finished updating '$basename'"
