#!/usr/bin/env fish

set -l script_dir (status dirname)

set -l url 'https://www.tweaking4all.com/home-theatre/rename-my-tv-series-v2/'
set -l regex 'RenameMyTVSeries-([\\d.]+)-Linux64bit\\.tar\\.gz'

echo 'Executing the `scrape_website` script'
set -l output_version ("$script_dir/../scripts/scrape_website" $url $regex 'a.btn-ok' 'href')

# @fish-lsp-disable-next-line 2001
set -l captured_version (sed -n 's/^Version:\\s*\\([\\d.]*\\)/\\1/p' "$script_dir/rename-my-tv-series.spec")

# @fish-lsp-disable-next-line 2001
echo 'Comparing captured version ($captured_version) with current version ($output_version)'
echo "Captured version: $captured_version"
echo "Current version: $output_version"
if test "$captured_version" != "$output_version" 
  echo 'Versions are different. Updating the spec file...'
  sd $captured_version $output_version "$script_dir/rename-my-tv-series.spec" && echo 'Done!'
else
  echo 'Both versions are the same. No update needed.'
end
