#!/usr/bin/env fish

set -l script_dir (status dirname)
set -l basename (basename "$script_dir")

echo "Updating '$basename'"

set -l url 'https://www.tweaking4all.com/home-theatre/rename-my-tv-series-v2/'
set -l regex 'RenameMyTVSeries-([\\d.]+)-Linux64bit\\.tar\\.gz'
set -l xpath '//div[@class="alert alert-success"]/table/tr/td[contains(text(),"RenameMyTVSeries")]'

echo 'Adding executable permissions to `parse-html`'
chmod +x "$script_dir/../scripts/parse-html"

echo 'Executing the `parse-html` script'
set -l output_version ("$script_dir/../scripts/parse-html" "$url" "$regex" "$xpath")

# @fish-lsp-disable-next-line 2001
set -l captured_version (sed -n 's/^Version:\\s*\\([\\d.]*\\)/\\1/p' "$script_dir/$basename.spec")

# @fish-lsp-disable-next-line 2001
echo 'Comparing captured version ($captured_version) with current version ($output_version)'
echo "Captured version: $captured_version"
echo "Current version: $output_version"
if test "$captured_version" != "$output_version" 
  echo 'Versions are different. Updating the spec file(s)...'
  for v in (fd '*.spec' "$script_dir")
    sd $captured_version $output_version "$script_dir/$v.spec"
  end && echo 'Done!'
else
  echo 'Both versions are the same. No update needed.'
end

echo 'Removing executable permissions from `parse-json`'
chmod -x "$script_dir/../scripts/parse-json"

echo "Finished updating '$basename'"
