#!/usr/bin/env python

import re
import sys
import xml.etree.ElementTree as xml
from lxml import html
import requests


def parse_xml(url: str, regex_str: str, xpath_expr: str):
    """
    Parses XML content from a URL and
    extracts the desired information using
    regular expressions and XPath expressions.
    """

    result = None

    # Compile the regular expression from string
    regex = re.compile(regex_str)

    # Invoke a new HTTP GET request
    response = requests.get(url)
    xml_content = xml.fromstring(response.content)

    #  Find all the elements that were captured the XPath expression
    elements = xml_content.findall(xpath_expr)

    for e in elements:
        # If you want the text content of the element:
        # print(element.text_content())
        # If you want the HTML representation of the element:
        v = xml.tostring(e).decode()

        matches = regex.search(v)

        if matches is not None: result = matches.group(1)  # noqa: E701

    print(result)
# end of parseWebContent

# Allow the user to pass in the arguments from the command line
parse_xml(sys.argv[1], sys.argv[2], sys.argv[3])
