name: 'Update packages'

on:
  schedule:
    # Runs every three hours at 01:00, 04:00, 07:00, 10:00, 13:00, 16:00, 19:00, and 22:00 UTC daily.
    - cron: '0 1,4,7,10,13,16,19,22 * * *'

  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      GITHUB_TOKEN: "${{ secrets.TOKEN }}"

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        with:
          repository: "${{ github.repository }}"
          token: "${{ env.GITHUB_TOKEN }}"

      - name: 'Install nix'
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: 'Install helper programs'
        shell: bash
        run: |
          echo '----- Installing helper programs -----'
          echo '> nix flake update --verbose'
          nix flake update --verbose
          echo '> nix profile install .'
          nix profile install .

      - name: 'Update package versions'
        shell: bash
        run: |
          echo '----- Installing Python packages -----'
          echo '> pip install uv'
          pip install uv
          echo '> cd ./scripts'
          cd ./scripts
          echo '> uv venv'
          uv venv
          echo '> source ./.venv/bin/activate'
          source ./.venv/bin/activate
          echo '> uv pip install -r ./requirements.txt'
          uv pip install -r ./requirements.txt
          echo '> cd ..'
          cd ..

          echo '---------------------------------------'
          echo '---------------------------------------'

          for i in $(fd 'update-script' .); do
            chmod +x $i
            echo "Executing $i"; $i
            chmod -x $i
            echo '---------------------------------------'
            echo '---------------------------------------'
          done

      - name: 'Commit changes'
        shell: bash
        run: |
          echo "> USERNAME='github-actions[bot]'"
          USERNAME='github-actions[bot]'
          echo "> EMAIL='41898282+github-actions[bot]@users.noreply.github.com'"
          EMAIL='41898282+github-actions[bot]@users.noreply.github.com'
          echo '> git config --local user.name $USERNAME'
          git config --local user.name $USERNAME
          echo '> git config --local user.email $EMAIL'
          git config --local user.email $EMAIL
          echo '> git add -u'
          git add -u
          if [ -n "$(git status --porcelain)" ]; then
            echo "> CURRENT_TIME=\$(date +'%Y-%m-%d %H:%M:%S')"
            CURRENT_TIME=$(date +'%Y-%m-%d %H:%M:%S')
            echo '> git commit -m "bot: Updated packages at $CURRENT_TIME"'
            git commit -m "bot: Updated packages at $CURRENT_TIME"
          fi

      - name: 'Push changes'
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: "${{ env.GITHUB_TOKEN }}"
          branch: "${{ github.ref }}"
